// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBw5AtVvCZz3ASyUhI8ey8DjHHg3HJDO0w',
    appId: '1:1074307967856:web:a7dc3bdb886ca348557db5',
    messagingSenderId: '1074307967856',
    projectId: 'montra-445ac',
    authDomain: 'montra-445ac.firebaseapp.com',
    storageBucket: 'montra-445ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJpLEPi551peotJsGPUooj7iqiQcaZwUA',
    appId: '1:1074307967856:android:30fdf7c72cf25438557db5',
    messagingSenderId: '1074307967856',
    projectId: 'montra-445ac',
    storageBucket: 'montra-445ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwKXXkgoVE5UzKtDyHfYlVyWEIlTMdiiI',
    appId: '1:1074307967856:ios:772e77cf37e5bb89557db5',
    messagingSenderId: '1074307967856',
    projectId: 'montra-445ac',
    storageBucket: 'montra-445ac.appspot.com',
    iosBundleId: 'com.example.montra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwKXXkgoVE5UzKtDyHfYlVyWEIlTMdiiI',
    appId: '1:1074307967856:ios:20b0f3d381186d98557db5',
    messagingSenderId: '1074307967856',
    projectId: 'montra-445ac',
    storageBucket: 'montra-445ac.appspot.com',
    iosBundleId: 'com.example.montra.RunnerTests',
  );
}
